name: Luma workflow
on:
    workflow_dispatch: # This allows manual triggering of the workflow
     
jobs:
    test:
        permissions:
            contents: read
            pages: write
            id-token: write
        runs-on: ubuntu-latest
        name: UI tests
        steps:
            - uses: actions/checkout@v3

            - name: Print working directory and list files (Debugging)
              run: |
                pwd
                ls -la  # List all files to ensure the correct files exist, especially wdio.conf.js

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: '18'  # Try using Node.js 18 if 20 is causing issues
                  cache: npm

            - name: Install packages
              run: npm install

            - name: Execute tests with npx
              run: npx wdio run wdio.conf.js  # Ensure the correct config file path

            - name: Install Allure CommandLine
              if: always()
              run: npm install -g allure-commandline

            - name: Combine Allure
              if: always()
              run: npm run allureCombine

            - name: Upload Test Report
              if: always()
              uses: actions/upload-artifact@v3
              with:
                  name: Allure report
                  path: test/.artifacts/allure-report/complete.html
